[book]
title = "User Guide to vhdl_doc"
description = "Specification and guide to the vhdl_doc comment documentation engine"
authors = ["n8tlarsen"]
language = "en"

[rust]
edition = "2024"

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/vhdl_doc/"
git-repository-url = "https://github.com/n8tlarsen/vhdl_doc/tree/master/guide"
edit-url-template = "https://github.com/n8tlarsen/vhdl_doc/edit/master/guide/{path}"
hash-files = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.code.hidelines]
python = "~"

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[output.html.redirect]
"/format/config.html" = "configuration/index.html"
